/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "outline": "rgb(var(--color-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "primary": "rgb(var(--color-primary) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-primary-container": "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--color-on-secondary-container) / <alpha-value>)",
        "inverse-surface": "rgb(var(--color-inverse-surface) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
        "error": "rgb(var(--color-error) / <alpha-value>)",
        "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
        "on-error": "rgb(var(--color-on-error) / <alpha-value>)",
        "on-error-container": "rgb(var(--color-on-error-container) / <alpha-value>)",
        "background": "rgb(var(--color-surface) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-surface) / <alpha-value>)",
        "secondary-fixed-dim": "#eac080",
        "secondary-fixed": "#ffdead",
        "primary-fixed": "#e6e2de",
        "surface-bright": "rgb(var(--color-surface) / <alpha-value>)",
        "surface-dim": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#261900",
        "on-tertiary-container": "#a17f3b",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-sm": "0.75rem",
        "space-lg": "2rem",
        "space-md": "1.25rem",
        "margin-mobile": "1.25rem",
        "margin": "3rem",
        "gutter": "1.5rem",
        "space-xs": "0.375rem",
        "space-xl": "3.5rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "body-md": [ "Plus Jakarta Sans", "sans-serif" ],
        "label-sm": [ "Plus Jakarta Sans", "sans-serif" ],
        "body-sm": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-lg": [ "EB Garamond", "serif" ],
        "label-md": [ "Plus Jakarta Sans", "sans-serif" ],
        "display": [ "EB Garamond", "serif" ],
        "headline-lg-mobile": [ "EB Garamond", "serif" ],
        "label-lg": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-sm": [ "EB Garamond", "serif" ],
        "body-lg": [ "Plus Jakarta Sans", "sans-serif" ],
        "display-mobile": [ "EB Garamond", "serif" ],
        "headline-md": [ "EB Garamond", "serif" ]
      },
      fontSize: {
        "body-md": [ "15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" } ],
        "label-sm": [ "10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" } ],
        "body-sm": [ "13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" } ],
        "headline-lg": [ "40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "400" } ],
        "label-md": [ "12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" } ],
        "display": [ "56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" } ],
        "headline-lg-mobile": [ "28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" } ],
        "label-lg": [ "14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "600" } ],
        "headline-sm": [ "22px", { lineHeight: "30px", letterSpacing: "0em", fontWeight: "500" } ],
        "body-lg": [ "18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" } ],
        "display-mobile": [ "40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "400" } ],
        "headline-md": [ "28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" } ]
      }
    }
  },
  plugins: [],
}
